### ISSUE TITLE
Approval from QA

### ISSUE THREAD

**Issue by reynaldicheok** [reynaldicheok/ETI-CA2#6]
Unit testing have been conducted and the todo features are running. Submit to QA for testing and bug findings.

**Comment by jonaisahhh** [comment]
Testing has been conducted by QA/PM (Jonaisah).

There are some minor issues required to be solved:
**Test Case ID:** Add-Item 1A (test_additem_1A)

S/NO | Action(s) | Input | Expected   Output | Actual   Output | Test   Result
-- | -- | -- | -- | -- | --
1 | Navigate Add/Delete To-Do page | Url: “http://localhost:8000/todo/” | System display Add/Delete To-Do page | System displays the To Do Page | Passed
2 | Input blank inputs | Description: ““   Category:””   Due Date:”” | System show blank inputs in the fields |   |  
3 | User adds item to page with blank details | User clicks add item button | System unable to add item due to blank input | System adds the blank inputs into the To Do list | Fail


**Test Case ID:** Add-Item 1B (test_additem_1B)

S/NO | Action(s) | Input | Expected   Output | Actual   Output | Test   Result
-- | -- | -- | -- | -- | --
1 | Navigate Add/Delete To-Do page | Url: “http://localhost:8000/todo/” | System display Add/Delete To-Do page | System displays the To Do Page | Passed
2 | Input valid description and category with due date before today’s   date. | Description: “Test program“   Category:”Testing”   Due Date: “1999/11/11” | System unable to add item due to expired due date | Not able to test as feature is not implemented | Fail


**Test Case ID:** Add-Item 1C (test_additem_1C)

S/NO | Action(s) | Input | Expected   Output | Actual   Output | Test   Result
-- | -- | -- | -- | -- | --
1 | Navigate Add/Delete To-Do page | Url: ““http://localhost:8000/todo/” | System display Add/Delete To-Do page | System displays the To Do Page | Passed
2 | User input Description, Category and due   date fields and click “Add Item” button | Description: “Test program“   Category:”Testing”   Due Date:”2020/4/1” | System display Inputs written in each   field | Not able to test as Description, Cateogory and due date fields are   not implemented | Fail
3 | User adds items with details input | User clicks “Add Item” button | System adds item in To-Do page | Not able to test as input fields is not implemented (S/NO 2) | Fail
4 | User checks item added earlier | Url: “http://localhost:8000/todo” | System displays added item | Not able to test as the input fields is not implemented (S/NO 2) | Fail


**Test Case ID:** Delete-Item 1B (test_deleteitem_1B)

S/NO | Action(s) | Input | Expected   Output | Actual   Output | Test   Result
-- | -- | -- | -- | -- | --
1 | Go to To-Do page | Url: “http://localhost:8000/todo/” | System display To-Do page | System displays the To Do Page | Passed
2 | User selects item selection | User selects item to be deleted | Tick is shown beside the selected item | No tick was shown however the item is deleted from the list |  
3 | User deletes the item | User clicks the delete button | System displays message that the item has   been deleted | The item is deleted.       No system message was shown with the deletion of the item | Fail
4 | User checks that item is deleted | Url: “http://localhost:8000/todo/” | System do not display item deleted in   To-Do page | System does not show the deleted item | Passed


**Test Case ID:** Archive-Item 1A (test_archiveitem_1A)

S/NO | Action(s) | Input | Expected   Output | Actual   Output | Test   Result
-- | -- | -- | -- | -- | --
1 | Go to To-Do page | Url: “http://localhost:8000/todo/” | System display To-Do page | System displays the To Do Page | Passed
2 | User selects item selection | User selects item to be archived | Tick is shown beside the selected item | Tick is not displayed beside the item to be archived | Fail
3 | User archives the item selected | User to click on the “archive” button | To show a message that item has been   archived and item is no longer shown in the list | Not able to test as the archive feature has not been implemented | Fail


Please refer to the Test Case IDs mentioned above in "Test case for CA2.docx"

**Comment by reynaldicheok** [comment]
Passed some test case, archival button has been removed for sprint 2 feature so is unable to be tested now.

**Comment by ShahrulNizamBR** [comment]
The test for Todo Page was conducted by Shahrul Q/A.

The five cases are working as expected with minor bugs in Test Case #4 in pytest: Test whether  item is deleted regarding the alert text.
